### ISSUE TITLE
Generator?

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-component-blueprint#1]
We're not creating new components every day but it might be nice to have some sort of generator, such as:

- `obt init --name name-of-the-component`
- `yo …`

**Comment by matthew-andrews** [comment]
I've been creating a few components regularly.  My workflow is:-

```
mkdir o-blah
cd o-blah
origami-build-tools verify
// fix errors
origami-build-tools verify
// fix errors
...

origami-build-tools verify
// success
origami-build-tools demo
// fix errors (ie. it'll tell you there is no config, so create a config file, then it'll be invalid, so create that…)
```

After not very much time (~10 mins), and after you've added each file/folder after knowing exactly why it's there and what it does you have a working Origami component…

I would advocate this approach over generators but other people may disagree :smile:
